###
file_storage: "local"       ### Options: "local", "s3"



###
cluster_type: "local"       ### Options: "local", "emr"
spark_version: "2.4.6"
hadoop_version: "2.7"
spark_dependencies:
  - "org.datasyslab:geospark:1.3.1"
  - "graphframes:graphframes:0.8.0-spark3.0-s_2.12"

spark_streaming_host: "localhost"
spark_streaming_port: 9999