name: Publish to Test PYPI

on:
  push:
    branches:
      - test_publish

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -U pip setuptools
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install build wheel twine 

      - name: Build package
        run: |
          python setup.py sdist bdist_wheel

      - name: Publish to Test PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI }}
        run: |
          twine upload -r testpypi dist/*

